name: chaoticnexus
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: chaoticnexus
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "10.0.0.196:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d chaoticnexus"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      FLASK_ENV: development
    ports:
      - "10.0.0.196:8080:8000"
    volumes:
      - ./_logs:/app/_logs
      - ./_data:/app/_data
    restart: unless-stopped
