[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
target-version = "py311"
line-length = 100

[tool.ruff.lint]
select = [
  "E",
  "F",
  "W",
  "B",
  "I",
  "UP",
]
ignore = [
  "B008",  # function-call-argument-default
]

[tool.isort]
profile = "black"
line_length = 100

