"""add updated_at to jobs and default for created_at

Revision ID: e2e67964d977
Revises: 6f59be1ae746
Create Date: 2025-10-13 05:19:59.439664

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e2e67964d977"
down_revision = "6f59be1ae746"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.alter_column("created_at", server_default=sa.text("now()"))

    # backfill any NULLs in created_at just in case
    op.execute("UPDATE jobs SET created_at = now() WHERE created_at IS NULL;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.alter_column("created_at", server_default=None)
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###
